FROM python:3.11-slim-bookworm
# FROM python:3.12


# Do not generate .pyc files and enable stdout buffering
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install system dependencies needed for psycopg2
# aslo cryptography require rust
# pydub require these two ==> ffmpeg (this installs both ffmpeg and ffprobe).

# pydub require these two ==> ffmpeg (this installs both ffmpeg and ffprobe).
RUN apt-get update \
    && apt-get install -y ffmpeg \
    && rm -rf /var/lib/apt/lists/*


# Copy only requirements from backend folder
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


# Copy code part
COPY backend/ ./backend/
COPY src/ ./src/

EXPOSE 8000

# /app/backend/app.py is the location of FastAPI app
CMD ["uvicorn", "backend.app:app", "--host", "0.0.0.0", "--port", "8000"]


# we are building from root directery
# docker build -t fastapi-backend -f backend/Dockerfile.fastapi .


#to run with .env
# docker run -p 8000:8000 --env-file .env fastapi-backend



# RUN apt-get update && apt-get install -y \
#     libpq-dev \
#     ffmpeg \
#     && rm -rf /var/lib/apt/lists/*